"""empty message

Revision ID: 203ecd622443
Revises: d9f6dc74b936
Create Date: 2024-08-19 20:48:45.337283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203ecd622443'
down_revision = 'd9f6dc74b936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.String(length=80),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
